Repository Plan-A-project/infli-server, pull requests merged in 2023-07, with the labels that each got.

#102 (#101) CORS OPTIONS 메서드 허용
  src/main/java/com/plana/infli/config/SecurityConfig.java
Labels: feat

#106 (#48) Post 관련 구현 2
  src/main/java/com/plana/infli/domain/Post.java
  src/main/java/com/plana/infli/domain/PostLike.java
  src/main/java/com/plana/infli/repository/post/PostRepository.java
  src/main/java/com/plana/infli/repository/postlike/PostLikeRepository.java
  src/main/java/com/plana/infli/service/PostLikeService.java
  src/main/java/com/plana/infli/service/PostService.java
  src/main/java/com/plana/infli/web/controller/PostController.java
  src/main/java/com/plana/infli/web/controller/PostLikeController.java
  src/main/java/com/plana/infli/web/dto/response/post/PostFindResponse.java
Labels: feat

#134 bug : 빌드 꺠짐 현상 해결 2
  src/test/java/com/plana/infli/service/MemberProfileServiceTest.java
Labels: bug

#142 Epic : 글 작성 권한 검증 API 코드 리펙토링 (#141)
  src/main/java/com/plana/infli/config/initializer/DefaultInitializer.java
  src/main/java/com/plana/infli/config/initializer/MemberInitializer.java
  src/main/java/com/plana/infli/domain/Board.java
  src/main/java/com/plana/infli/domain/BoardType.java
  src/main/java/com/plana/infli/domain/Member.java
  src/main/java/com/plana/infli/domain/PostType.java
  src/main/java/com/plana/infli/domain/Role.java
  src/main/java/com/plana/infli/service/BoardService.java
  src/main/java/com/plana/infli/service/PostService.java
  src/main/java/com/plana/infli/web/controller/BoardController.java
  src/main/java/com/plana/infli/web/controller/PostController.java
  src/main/java/com/plana/infli/web/dto/request/post/create/CreatePostRequest.java
  src/main/java/com/plana/infli/web/dto/request/post/edit/EditPostRequest.java
  src/main/java/com/plana/infli/web/dto/request/post/view/board/LoadPostsByBoardRequest.java
  src/main/java/com/plana/infli/web/dto/request/post/view/search/SearchPostsByKeywordRequest.java
  src/test/java/com/plana/infli/controller/BoardControllerTest.java
Labels: chore
