Repository Plan-A-project/infli-server, pull requests merged in 2023-06, with the labels that each got.

#5 (#1) 프로젝트 초기 설정
  .gitignore
  .gitsecret/keys/pubring.kbx
  .gitsecret/keys/trustdb.gpg
  .gitsecret/paths/mapping.cfg
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/plana/infli/InfliApplication.java
  src/main/java/com/plana/infli/config/SecurityConfig.java
  src/main/resources/application.yml.secret
  src/test/java/com/plana/infli/InfliApplicationTests.java
Labels: chore

#24 (#20) 스프링 부트 초기 설정 3
  .gitignore
  .gitsecret/keys/pubring.kbx
  .gitsecret/keys/trustdb.gpg
  .gitsecret/paths/mapping.cfg
  build.gradle
  src/main/generated/com/plana/infli/domain/QBaseEntity.java
  src/main/generated/com/plana/infli/domain/QBoard.java
  src/main/generated/com/plana/infli/domain/QEmailAuthentication.java
  src/main/generated/com/plana/infli/domain/QMember.java
  src/main/generated/com/plana/infli/domain/QUniversity.java
  src/main/java/com/plana/infli/domain/EmailAuthentication.java
  src/main/java/com/plana/infli/domain/Member.java
  src/main/java/com/plana/infli/domain/Role.java
  src/main/resources/application.yml.secret
Labels: chore, feat

#60 (#59) spring cloud config 적용
  .gitignore
  build.gradle
  src/main/generated/com/plana/infli/domain/QBaseEntity.java
  src/main/generated/com/plana/infli/domain/QBoard.java
  src/main/generated/com/plana/infli/domain/QComment.java
  src/main/generated/com/plana/infli/domain/QEmailAuthentication.java
  src/main/generated/com/plana/infli/domain/QMember.java
  src/main/generated/com/plana/infli/domain/QMemberBoard.java
  src/main/generated/com/plana/infli/domain/QPost.java
  src/main/generated/com/plana/infli/domain/QPostLike.java
  src/main/generated/com/plana/infli/domain/QUniversity.java
  src/main/generated/com/plana/infli/web/dto/response/board/all/QSingleBoard.java
  src/main/generated/com/plana/infli/web/dto/response/board/member/QMemberSingleBoard.java
  src/main/java/com/plana/infli/domain/MemberBoard.java
  src/main/resources/application.yml
Labels: chore

#65 (#16) 이미지 관련 기능 작업
  .gitignore
  src/main/java/com/plana/infli/config/AWSConfig.java
  src/main/java/com/plana/infli/domain/Image.java
  src/main/java/com/plana/infli/repository/post/ImageRepository.java
  src/main/java/com/plana/infli/service/ImageService.java
  src/main/java/com/plana/infli/utils/S3Uploader.java
  src/main/java/com/plana/infli/web/controller/ImageController.java
  src/main/java/com/plana/infli/web/dto/request/image/ImageCreateRs.java
Labels: feat

#66 멤버 인증 관련 API 구현 (#25)
  .gitignore
  src/main/java/com/plana/infli/config/MvcConfig.java
  src/main/java/com/plana/infli/config/RedisConfig.java
  src/main/java/com/plana/infli/config/SecurityConfig.java
  src/main/java/com/plana/infli/domain/Comment.java
  src/main/java/com/plana/infli/domain/EmailAuthentication.java
  src/main/java/com/plana/infli/domain/Image.java
  src/main/java/com/plana/infli/domain/Member.java
  src/main/java/com/plana/infli/exception/advice/DefaultExceptionAdvice.java
  src/main/java/com/plana/infli/exception/advice/ExceptionAdvice.java
  src/main/java/com/plana/infli/exception/advice/ValidationExceptionAdvice.java
  src/main/java/com/plana/infli/exception/custom/ConflictException.java
  src/main/java/com/plana/infli/exception/custom/NotFoundException.java
  src/main/java/com/plana/infli/repository/email_authentication/EmailAuthenticationRepository.java
  src/main/java/com/plana/infli/repository/email_authentication/EmailAuthenticationRepositoryCustom.java
  src/main/java/com/plana/infli/repository/email_authentication/EmailAuthenticationRepositoryImpl.java
  src/main/java/com/plana/infli/repository/member/MemberRepository.java
  src/main/java/com/plana/infli/repository/redis/RedisDao.java
  src/main/java/com/plana/infli/security/CustomAuthenticationEntryPoint.java
  src/main/java/com/plana/infli/security/JsonLoginFailureHandler.java
  src/main/java/com/plana/infli/security/JsonLoginProcessingFilter.java
  src/main/java/com/plana/infli/security/UserDetailServiceImpl.java
  src/main/java/com/plana/infli/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/plana/infli/security/jwt/JwtExceptionHandlerFilter.java
  src/main/java/com/plana/infli/security/jwt/JwtLoginSuccessHandler.java
  src/main/java/com/plana/infli/security/jwt/JwtManager.java
  src/main/java/com/plana/infli/security/jwt/JwtProperties.java
  src/main/java/com/plana/infli/security/jwt/JwtTokenExpiredEntrypoint.java
  src/main/java/com/plana/infli/service/AuthService.java
  src/main/java/com/plana/infli/service/ImageService.java
  src/main/java/com/plana/infli/service/MailService.java
  src/main/java/com/plana/infli/service/MemberService.java
  src/main/java/com/plana/infli/service/validator/comment/CreateCommentValidator.java
  src/main/java/com/plana/infli/web/controller/AuthController.java
  src/main/java/com/plana/infli/web/controller/MemberController.java
  src/main/java/com/plana/infli/web/dto/request/member/MemberCreateRequest.java
  src/main/java/com/plana/infli/web/dto/request/member/StudentAuthenticationRequest.java
  src/main/java/com/plana/infli/web/dto/response/error/ErrorResponse.java
  src/main/java/com/plana/infli/web/dto/response/member/MemberCreateResponse.java
  src/main/java/com/plana/infli/web/resolver/AuthenticatedPrincipal.java
  src/main/java/com/plana/infli/web/resolver/PrincipalHandlerMethodArgumentResolver.java
Labels: feat

#69 (#44) Post 관련 구현 1
  src/main/java/com/plana/infli/domain/Post.java
  src/main/java/com/plana/infli/domain/PostType.java
  src/main/java/com/plana/infli/service/PostService.java
  src/main/java/com/plana/infli/web/controller/PostController.java
  src/main/java/com/plana/infli/web/dto/request/post/GatherPostCreateRq.java
  src/main/java/com/plana/infli/web/dto/request/post/PostCreateRq.java
Labels: feat
